// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v6.33.1
// source: grpc/engine.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_OPERATION_UNSPECIFIED     Operation = 0
	Operation_OPERATION_GET_OBJECTS     Operation = 1
	Operation_OPERATION_ADD_OBJECT      Operation = 2
	Operation_OPERATION_REMOVE_OBJECT   Operation = 3
	Operation_OPERATION_MOVE_OBJECT     Operation = 4
	Operation_OPERATION_ROTATE_OBJECT   Operation = 5
	Operation_OPERATION_SCALE_OBJECT    Operation = 6
	Operation_OPERATION_UPDATE_OBJECT   Operation = 7
	Operation_OPERATION_LOAD_SCENE      Operation = 8
	Operation_OPERATION_GET_SCENE_MODES Operation = 9
	Operation_OPERATION_LOAD_SCENE_MODE Operation = 10
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0:  "OPERATION_UNSPECIFIED",
		1:  "OPERATION_GET_OBJECTS",
		2:  "OPERATION_ADD_OBJECT",
		3:  "OPERATION_REMOVE_OBJECT",
		4:  "OPERATION_MOVE_OBJECT",
		5:  "OPERATION_ROTATE_OBJECT",
		6:  "OPERATION_SCALE_OBJECT",
		7:  "OPERATION_UPDATE_OBJECT",
		8:  "OPERATION_LOAD_SCENE",
		9:  "OPERATION_GET_SCENE_MODES",
		10: "OPERATION_LOAD_SCENE_MODE",
	}
	Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED":     0,
		"OPERATION_GET_OBJECTS":     1,
		"OPERATION_ADD_OBJECT":      2,
		"OPERATION_REMOVE_OBJECT":   3,
		"OPERATION_MOVE_OBJECT":     4,
		"OPERATION_ROTATE_OBJECT":   5,
		"OPERATION_SCALE_OBJECT":    6,
		"OPERATION_UPDATE_OBJECT":   7,
		"OPERATION_LOAD_SCENE":      8,
		"OPERATION_GET_SCENE_MODES": 9,
		"OPERATION_LOAD_SCENE_MODE": 10,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_engine_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_grpc_engine_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{0}
}

type EngineRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Operation Operation              `protobuf:"varint,1,opt,name=operation,proto3,enum=grpc.Operation" json:"operation,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*EngineRequest_Empty
	//	*EngineRequest_Object
	//	*EngineRequest_Scene
	//	*EngineRequest_SceneMode
	Body          isEngineRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineRequest) Reset() {
	*x = EngineRequest{}
	mi := &file_grpc_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineRequest) ProtoMessage() {}

func (x *EngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineRequest.ProtoReflect.Descriptor instead.
func (*EngineRequest) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{0}
}

func (x *EngineRequest) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_OPERATION_UNSPECIFIED
}

func (x *EngineRequest) GetBody() isEngineRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *EngineRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Body.(*EngineRequest_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

func (x *EngineRequest) GetObject() *Object {
	if x != nil {
		if x, ok := x.Body.(*EngineRequest_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *EngineRequest) GetScene() *SceneRef {
	if x != nil {
		if x, ok := x.Body.(*EngineRequest_Scene); ok {
			return x.Scene
		}
	}
	return nil
}

func (x *EngineRequest) GetSceneMode() *SceneModeRef {
	if x != nil {
		if x, ok := x.Body.(*EngineRequest_SceneMode); ok {
			return x.SceneMode
		}
	}
	return nil
}

type isEngineRequest_Body interface {
	isEngineRequest_Body()
}

type EngineRequest_Empty struct {
	Empty *emptypb.Empty `protobuf:"bytes,2,opt,name=empty,proto3,oneof"`
}

type EngineRequest_Object struct {
	Object *Object `protobuf:"bytes,3,opt,name=object,proto3,oneof"`
}

type EngineRequest_Scene struct {
	Scene *SceneRef `protobuf:"bytes,4,opt,name=scene,proto3,oneof"`
}

type EngineRequest_SceneMode struct {
	SceneMode *SceneModeRef `protobuf:"bytes,5,opt,name=scene_mode,json=sceneMode,proto3,oneof"`
}

func (*EngineRequest_Empty) isEngineRequest_Body() {}

func (*EngineRequest_Object) isEngineRequest_Body() {}

func (*EngineRequest_Scene) isEngineRequest_Body() {}

func (*EngineRequest_SceneMode) isEngineRequest_Body() {}

type EngineResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Operation Operation              `protobuf:"varint,1,opt,name=operation,proto3,enum=grpc.Operation" json:"operation,omitempty"`
	Success   bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error     string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*EngineResponse_Empty
	//	*EngineResponse_Objects
	//	*EngineResponse_Object
	//	*EngineResponse_SceneModes
	Body          isEngineResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineResponse) Reset() {
	*x = EngineResponse{}
	mi := &file_grpc_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineResponse) ProtoMessage() {}

func (x *EngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineResponse.ProtoReflect.Descriptor instead.
func (*EngineResponse) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{1}
}

func (x *EngineResponse) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_OPERATION_UNSPECIFIED
}

func (x *EngineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EngineResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EngineResponse) GetBody() isEngineResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *EngineResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Body.(*EngineResponse_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

func (x *EngineResponse) GetObjects() *Objects {
	if x != nil {
		if x, ok := x.Body.(*EngineResponse_Objects); ok {
			return x.Objects
		}
	}
	return nil
}

func (x *EngineResponse) GetObject() *Object {
	if x != nil {
		if x, ok := x.Body.(*EngineResponse_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *EngineResponse) GetSceneModes() *SceneModes {
	if x != nil {
		if x, ok := x.Body.(*EngineResponse_SceneModes); ok {
			return x.SceneModes
		}
	}
	return nil
}

type isEngineResponse_Body interface {
	isEngineResponse_Body()
}

type EngineResponse_Empty struct {
	Empty *emptypb.Empty `protobuf:"bytes,4,opt,name=empty,proto3,oneof"`
}

type EngineResponse_Objects struct {
	Objects *Objects `protobuf:"bytes,5,opt,name=objects,proto3,oneof"`
}

type EngineResponse_Object struct {
	Object *Object `protobuf:"bytes,6,opt,name=object,proto3,oneof"`
}

type EngineResponse_SceneModes struct {
	SceneModes *SceneModes `protobuf:"bytes,7,opt,name=scene_modes,json=sceneModes,proto3,oneof"`
}

func (*EngineResponse_Empty) isEngineResponse_Body() {}

func (*EngineResponse_Objects) isEngineResponse_Body() {}

func (*EngineResponse_Object) isEngineResponse_Body() {}

func (*EngineResponse_SceneModes) isEngineResponse_Body() {}

type Objects struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*Object              `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Objects) Reset() {
	*x = Objects{}
	mi := &file_grpc_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Objects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Objects) ProtoMessage() {}

func (x *Objects) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Objects.ProtoReflect.Descriptor instead.
func (*Objects) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{2}
}

func (x *Objects) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

type Object struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_grpc_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{3}
}

func (x *Object) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Object) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Object) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Vector3               `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Rotation      *Vector4               `protobuf:"bytes,2,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Scale         *Vector3               `protobuf:"bytes,3,opt,name=scale,proto3" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_grpc_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{4}
}

func (x *Location) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Location) GetRotation() *Vector4 {
	if x != nil {
		return x.Rotation
	}
	return nil
}

func (x *Location) GetScale() *Vector3 {
	if x != nil {
		return x.Scale
	}
	return nil
}

type Vector4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	W             float32                `protobuf:"fixed32,4,opt,name=w,proto3" json:"w,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector4) Reset() {
	*x = Vector4{}
	mi := &file_grpc_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector4) ProtoMessage() {}

func (x *Vector4) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector4.ProtoReflect.Descriptor instead.
func (*Vector4) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{5}
}

func (x *Vector4) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector4) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector4) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Vector4) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_grpc_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{6}
}

func (x *Vector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type SceneRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneRef) Reset() {
	*x = SceneRef{}
	mi := &file_grpc_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneRef) ProtoMessage() {}

func (x *SceneRef) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneRef.ProtoReflect.Descriptor instead.
func (*SceneRef) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{7}
}

func (x *SceneRef) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SceneModeRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneModeRef) Reset() {
	*x = SceneModeRef{}
	mi := &file_grpc_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneModeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneModeRef) ProtoMessage() {}

func (x *SceneModeRef) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneModeRef.ProtoReflect.Descriptor instead.
func (*SceneModeRef) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{8}
}

func (x *SceneModeRef) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type SceneMode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneMode) Reset() {
	*x = SceneMode{}
	mi := &file_grpc_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneMode) ProtoMessage() {}

func (x *SceneMode) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneMode.ProtoReflect.Descriptor instead.
func (*SceneMode) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{9}
}

func (x *SceneMode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SceneMode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SceneModes struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Modes            []*SceneMode           `protobuf:"bytes,1,rep,name=modes,proto3" json:"modes,omitempty"`
	CurrentMode      string                 `protobuf:"bytes,2,opt,name=current_mode,json=currentMode,proto3" json:"current_mode,omitempty"`
	CurrentScenePath string                 `protobuf:"bytes,3,opt,name=current_scene_path,json=currentScenePath,proto3" json:"current_scene_path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SceneModes) Reset() {
	*x = SceneModes{}
	mi := &file_grpc_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneModes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneModes) ProtoMessage() {}

func (x *SceneModes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneModes.ProtoReflect.Descriptor instead.
func (*SceneModes) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{10}
}

func (x *SceneModes) GetModes() []*SceneMode {
	if x != nil {
		return x.Modes
	}
	return nil
}

func (x *SceneModes) GetCurrentMode() string {
	if x != nil {
		return x.CurrentMode
	}
	return ""
}

func (x *SceneModes) GetCurrentScenePath() string {
	if x != nil {
		return x.CurrentScenePath
	}
	return ""
}

var File_grpc_engine_proto protoreflect.FileDescriptor

var file_grpc_engine_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfb, 0x01, 0x0a, 0x0d, 0x45, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00,
	0x52, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x26, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x26, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x48, 0x00,
	0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x73, 0x63, 0x65, 0x6e, 0x65,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x66, 0x48,
	0x00, 0x52, 0x09, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x42, 0x06, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x22, 0xaf, 0x02, 0x0a, 0x0e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x29, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x48, 0x00, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x12, 0x26, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48,
	0x00, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x33, 0x0a, 0x0b, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x73,
	0x48, 0x00, 0x52, 0x0a, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x73, 0x42, 0x06,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x31, 0x0a, 0x07, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x12, 0x26, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x58, 0x0a, 0x06, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x85, 0x01, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x29, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x33, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x08, 0x72,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x34, 0x52, 0x08, 0x72, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x33, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x22, 0x41, 0x0a, 0x07, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x34, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a,
	0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x77, 0x22, 0x33,
	0x0a, 0x07, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x7a, 0x22, 0x1e, 0x0a, 0x08, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x66, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x22, 0x22, 0x0a, 0x0c, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x33, 0x0a, 0x09, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x84, 0x01, 0x0a,
	0x0a, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x5f, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x2a, 0xc1, 0x02, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x19, 0x0a, 0x15, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15,
	0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x4f, 0x42,
	0x4a, 0x45, 0x43, 0x54, 0x53, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x4f, 0x50, 0x45, 0x52, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x44, 0x44, 0x5f, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x10,
	0x02, 0x12, 0x1b, 0x0a, 0x17, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52,
	0x45, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x03, 0x12, 0x19,
	0x0a, 0x15, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4d, 0x4f, 0x56, 0x45,
	0x5f, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x04, 0x12, 0x1b, 0x0a, 0x17, 0x4f, 0x50, 0x45,
	0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52, 0x4f, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x42,
	0x4a, 0x45, 0x43, 0x54, 0x10, 0x05, 0x12, 0x1a, 0x0a, 0x16, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x43, 0x41, 0x4c, 0x45, 0x5f, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54,
	0x10, 0x06, 0x12, 0x1b, 0x0a, 0x17, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x07, 0x12,
	0x18, 0x0a, 0x14, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4c, 0x4f, 0x41,
	0x44, 0x5f, 0x53, 0x43, 0x45, 0x4e, 0x45, 0x10, 0x08, 0x12, 0x1d, 0x0a, 0x19, 0x4f, 0x50, 0x45,
	0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x53, 0x43, 0x45, 0x4e, 0x45,
	0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x53, 0x10, 0x09, 0x12, 0x1d, 0x0a, 0x19, 0x4f, 0x50, 0x45, 0x52,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x53, 0x43, 0x45, 0x4e, 0x45,
	0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x10, 0x0a, 0x32, 0x41, 0x0a, 0x06, 0x45, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x12, 0x37, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x13, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x10, 0x5a, 0x0e, 0x33, 0x64,
	0x2d, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_engine_proto_rawDescOnce sync.Once
	file_grpc_engine_proto_rawDescData = file_grpc_engine_proto_rawDesc
)

func file_grpc_engine_proto_rawDescGZIP() []byte {
	file_grpc_engine_proto_rawDescOnce.Do(func() {
		file_grpc_engine_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_engine_proto_rawDescData)
	})
	return file_grpc_engine_proto_rawDescData
}

var file_grpc_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_grpc_engine_proto_goTypes = []any{
	(Operation)(0),         // 0: grpc.Operation
	(*EngineRequest)(nil),  // 1: grpc.EngineRequest
	(*EngineResponse)(nil), // 2: grpc.EngineResponse
	(*Objects)(nil),        // 3: grpc.Objects
	(*Object)(nil),         // 4: grpc.Object
	(*Location)(nil),       // 5: grpc.Location
	(*Vector4)(nil),        // 6: grpc.Vector4
	(*Vector3)(nil),        // 7: grpc.Vector3
	(*SceneRef)(nil),       // 8: grpc.SceneRef
	(*SceneModeRef)(nil),   // 9: grpc.SceneModeRef
	(*SceneMode)(nil),      // 10: grpc.SceneMode
	(*SceneModes)(nil),     // 11: grpc.SceneModes
	(*emptypb.Empty)(nil),  // 12: google.protobuf.Empty
}
var file_grpc_engine_proto_depIdxs = []int32{
	0,  // 0: grpc.EngineRequest.operation:type_name -> grpc.Operation
	12, // 1: grpc.EngineRequest.empty:type_name -> google.protobuf.Empty
	4,  // 2: grpc.EngineRequest.object:type_name -> grpc.Object
	8,  // 3: grpc.EngineRequest.scene:type_name -> grpc.SceneRef
	9,  // 4: grpc.EngineRequest.scene_mode:type_name -> grpc.SceneModeRef
	0,  // 5: grpc.EngineResponse.operation:type_name -> grpc.Operation
	12, // 6: grpc.EngineResponse.empty:type_name -> google.protobuf.Empty
	3,  // 7: grpc.EngineResponse.objects:type_name -> grpc.Objects
	4,  // 8: grpc.EngineResponse.object:type_name -> grpc.Object
	11, // 9: grpc.EngineResponse.scene_modes:type_name -> grpc.SceneModes
	4,  // 10: grpc.Objects.objects:type_name -> grpc.Object
	5,  // 11: grpc.Object.location:type_name -> grpc.Location
	7,  // 12: grpc.Location.position:type_name -> grpc.Vector3
	6,  // 13: grpc.Location.rotation:type_name -> grpc.Vector4
	7,  // 14: grpc.Location.scale:type_name -> grpc.Vector3
	10, // 15: grpc.SceneModes.modes:type_name -> grpc.SceneMode
	1,  // 16: grpc.Engine.Stream:input_type -> grpc.EngineRequest
	2,  // 17: grpc.Engine.Stream:output_type -> grpc.EngineResponse
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_grpc_engine_proto_init() }
func file_grpc_engine_proto_init() {
	if File_grpc_engine_proto != nil {
		return
	}
	file_grpc_engine_proto_msgTypes[0].OneofWrappers = []any{
		(*EngineRequest_Empty)(nil),
		(*EngineRequest_Object)(nil),
		(*EngineRequest_Scene)(nil),
		(*EngineRequest_SceneMode)(nil),
	}
	file_grpc_engine_proto_msgTypes[1].OneofWrappers = []any{
		(*EngineResponse_Empty)(nil),
		(*EngineResponse_Objects)(nil),
		(*EngineResponse_Object)(nil),
		(*EngineResponse_SceneModes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_engine_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_engine_proto_goTypes,
		DependencyIndexes: file_grpc_engine_proto_depIdxs,
		EnumInfos:         file_grpc_engine_proto_enumTypes,
		MessageInfos:      file_grpc_engine_proto_msgTypes,
	}.Build()
	File_grpc_engine_proto = out.File
	file_grpc_engine_proto_rawDesc = nil
	file_grpc_engine_proto_goTypes = nil
	file_grpc_engine_proto_depIdxs = nil
}
