// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: grpc/engine.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_OPERATION_UNSPECIFIED     Operation = 0
	Operation_OPERATION_GET_OBJECTS     Operation = 1
	Operation_OPERATION_ADD_OBJECT      Operation = 2
	Operation_OPERATION_REMOVE_OBJECT   Operation = 3
	Operation_OPERATION_MOVE_OBJECT     Operation = 4
	Operation_OPERATION_ROTATE_OBJECT   Operation = 5
	Operation_OPERATION_SCALE_OBJECT    Operation = 6
	Operation_OPERATION_UPDATE_OBJECT   Operation = 7
	Operation_OPERATION_LOAD_SCENE      Operation = 8
	Operation_OPERATION_GET_SCENE_MODES Operation = 9
	Operation_OPERATION_LOAD_SCENE_MODE Operation = 10
	// Reparent an existing object. object.id is the child, object.parent_id the
	// new parent; a parent_id of 0 detaches it to the scene root.
	Operation_OPERATION_SET_PARENT Operation = 11
	// Remove an object together with everything below it. REMOVE_OBJECT leaves
	// the children behind, lifted to the scene root.
	Operation_OPERATION_REMOVE_TREE Operation = 12
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0:  "OPERATION_UNSPECIFIED",
		1:  "OPERATION_GET_OBJECTS",
		2:  "OPERATION_ADD_OBJECT",
		3:  "OPERATION_REMOVE_OBJECT",
		4:  "OPERATION_MOVE_OBJECT",
		5:  "OPERATION_ROTATE_OBJECT",
		6:  "OPERATION_SCALE_OBJECT",
		7:  "OPERATION_UPDATE_OBJECT",
		8:  "OPERATION_LOAD_SCENE",
		9:  "OPERATION_GET_SCENE_MODES",
		10: "OPERATION_LOAD_SCENE_MODE",
		11: "OPERATION_SET_PARENT",
		12: "OPERATION_REMOVE_TREE",
	}
	Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED":     0,
		"OPERATION_GET_OBJECTS":     1,
		"OPERATION_ADD_OBJECT":      2,
		"OPERATION_REMOVE_OBJECT":   3,
		"OPERATION_MOVE_OBJECT":     4,
		"OPERATION_ROTATE_OBJECT":   5,
		"OPERATION_SCALE_OBJECT":    6,
		"OPERATION_UPDATE_OBJECT":   7,
		"OPERATION_LOAD_SCENE":      8,
		"OPERATION_GET_SCENE_MODES": 9,
		"OPERATION_LOAD_SCENE_MODE": 10,
		"OPERATION_SET_PARENT":      11,
		"OPERATION_REMOVE_TREE":     12,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_engine_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_grpc_engine_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{0}
}

type EngineRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Operation Operation              `protobuf:"varint,1,opt,name=operation,proto3,enum=grpc.Operation" json:"operation,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*EngineRequest_Empty
	//	*EngineRequest_Object
	//	*EngineRequest_Scene
	//	*EngineRequest_SceneMode
	Body          isEngineRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineRequest) Reset() {
	*x = EngineRequest{}
	mi := &file_grpc_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineRequest) ProtoMessage() {}

func (x *EngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineRequest.ProtoReflect.Descriptor instead.
func (*EngineRequest) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{0}
}

func (x *EngineRequest) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_OPERATION_UNSPECIFIED
}

func (x *EngineRequest) GetBody() isEngineRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *EngineRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Body.(*EngineRequest_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

func (x *EngineRequest) GetObject() *Object {
	if x != nil {
		if x, ok := x.Body.(*EngineRequest_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *EngineRequest) GetScene() *SceneRef {
	if x != nil {
		if x, ok := x.Body.(*EngineRequest_Scene); ok {
			return x.Scene
		}
	}
	return nil
}

func (x *EngineRequest) GetSceneMode() *SceneModeRef {
	if x != nil {
		if x, ok := x.Body.(*EngineRequest_SceneMode); ok {
			return x.SceneMode
		}
	}
	return nil
}

type isEngineRequest_Body interface {
	isEngineRequest_Body()
}

type EngineRequest_Empty struct {
	Empty *emptypb.Empty `protobuf:"bytes,2,opt,name=empty,proto3,oneof"`
}

type EngineRequest_Object struct {
	Object *Object `protobuf:"bytes,3,opt,name=object,proto3,oneof"`
}

type EngineRequest_Scene struct {
	Scene *SceneRef `protobuf:"bytes,4,opt,name=scene,proto3,oneof"`
}

type EngineRequest_SceneMode struct {
	SceneMode *SceneModeRef `protobuf:"bytes,5,opt,name=scene_mode,json=sceneMode,proto3,oneof"`
}

func (*EngineRequest_Empty) isEngineRequest_Body() {}

func (*EngineRequest_Object) isEngineRequest_Body() {}

func (*EngineRequest_Scene) isEngineRequest_Body() {}

func (*EngineRequest_SceneMode) isEngineRequest_Body() {}

type EngineResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Operation Operation              `protobuf:"varint,1,opt,name=operation,proto3,enum=grpc.Operation" json:"operation,omitempty"`
	Success   bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error     string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*EngineResponse_Empty
	//	*EngineResponse_Objects
	//	*EngineResponse_Object
	//	*EngineResponse_SceneModes
	Body          isEngineResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineResponse) Reset() {
	*x = EngineResponse{}
	mi := &file_grpc_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineResponse) ProtoMessage() {}

func (x *EngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineResponse.ProtoReflect.Descriptor instead.
func (*EngineResponse) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{1}
}

func (x *EngineResponse) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_OPERATION_UNSPECIFIED
}

func (x *EngineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EngineResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EngineResponse) GetBody() isEngineResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *EngineResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Body.(*EngineResponse_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

func (x *EngineResponse) GetObjects() *Objects {
	if x != nil {
		if x, ok := x.Body.(*EngineResponse_Objects); ok {
			return x.Objects
		}
	}
	return nil
}

func (x *EngineResponse) GetObject() *Object {
	if x != nil {
		if x, ok := x.Body.(*EngineResponse_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *EngineResponse) GetSceneModes() *SceneModes {
	if x != nil {
		if x, ok := x.Body.(*EngineResponse_SceneModes); ok {
			return x.SceneModes
		}
	}
	return nil
}

type isEngineResponse_Body interface {
	isEngineResponse_Body()
}

type EngineResponse_Empty struct {
	Empty *emptypb.Empty `protobuf:"bytes,4,opt,name=empty,proto3,oneof"`
}

type EngineResponse_Objects struct {
	Objects *Objects `protobuf:"bytes,5,opt,name=objects,proto3,oneof"`
}

type EngineResponse_Object struct {
	Object *Object `protobuf:"bytes,6,opt,name=object,proto3,oneof"`
}

type EngineResponse_SceneModes struct {
	SceneModes *SceneModes `protobuf:"bytes,7,opt,name=scene_modes,json=sceneModes,proto3,oneof"`
}

func (*EngineResponse_Empty) isEngineResponse_Body() {}

func (*EngineResponse_Objects) isEngineResponse_Body() {}

func (*EngineResponse_Object) isEngineResponse_Body() {}

func (*EngineResponse_SceneModes) isEngineResponse_Body() {}

type Objects struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*Object              `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Objects) Reset() {
	*x = Objects{}
	mi := &file_grpc_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Objects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Objects) ProtoMessage() {}

func (x *Objects) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Objects.ProtoReflect.Descriptor instead.
func (*Objects) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{2}
}

func (x *Objects) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

type Object struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id       uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Location *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	// Asset path, used by ADD_OBJECT to say what to load. Populated on read so a
	// client can round-trip an object it fetched.
	Model string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	// Encoded handle of this object's parent, or 0 when it sits at the scene
	// root. GET_OBJECTS returns the world flat — the same way the engine stores
	// it — and this is what lets a client rebuild the tree. ADD_OBJECT reads it to
	// attach the new object under an existing one.
	//
	// Note that `location` is the object's LOCAL transform, so a child of a moving
	// parent reports a constant position while sweeping through the world.
	ParentId      uint64 `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_grpc_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{3}
}

func (x *Object) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Object) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Object) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Object) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Object) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Vector3               `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Rotation      *Vector4               `protobuf:"bytes,2,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Scale         *Vector3               `protobuf:"bytes,3,opt,name=scale,proto3" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_grpc_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{4}
}

func (x *Location) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Location) GetRotation() *Vector4 {
	if x != nil {
		return x.Rotation
	}
	return nil
}

func (x *Location) GetScale() *Vector3 {
	if x != nil {
		return x.Scale
	}
	return nil
}

type Vector4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	W             float32                `protobuf:"fixed32,4,opt,name=w,proto3" json:"w,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector4) Reset() {
	*x = Vector4{}
	mi := &file_grpc_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector4) ProtoMessage() {}

func (x *Vector4) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector4.ProtoReflect.Descriptor instead.
func (*Vector4) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{5}
}

func (x *Vector4) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector4) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector4) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Vector4) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_grpc_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{6}
}

func (x *Vector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type SceneRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneRef) Reset() {
	*x = SceneRef{}
	mi := &file_grpc_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneRef) ProtoMessage() {}

func (x *SceneRef) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneRef.ProtoReflect.Descriptor instead.
func (*SceneRef) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{7}
}

func (x *SceneRef) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SceneModeRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneModeRef) Reset() {
	*x = SceneModeRef{}
	mi := &file_grpc_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneModeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneModeRef) ProtoMessage() {}

func (x *SceneModeRef) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneModeRef.ProtoReflect.Descriptor instead.
func (*SceneModeRef) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{8}
}

func (x *SceneModeRef) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type SceneMode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneMode) Reset() {
	*x = SceneMode{}
	mi := &file_grpc_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneMode) ProtoMessage() {}

func (x *SceneMode) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneMode.ProtoReflect.Descriptor instead.
func (*SceneMode) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{9}
}

func (x *SceneMode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SceneMode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SceneModes struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Modes            []*SceneMode           `protobuf:"bytes,1,rep,name=modes,proto3" json:"modes,omitempty"`
	CurrentMode      string                 `protobuf:"bytes,2,opt,name=current_mode,json=currentMode,proto3" json:"current_mode,omitempty"`
	CurrentScenePath string                 `protobuf:"bytes,3,opt,name=current_scene_path,json=currentScenePath,proto3" json:"current_scene_path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SceneModes) Reset() {
	*x = SceneModes{}
	mi := &file_grpc_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneModes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneModes) ProtoMessage() {}

func (x *SceneModes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneModes.ProtoReflect.Descriptor instead.
func (*SceneModes) Descriptor() ([]byte, []int) {
	return file_grpc_engine_proto_rawDescGZIP(), []int{10}
}

func (x *SceneModes) GetModes() []*SceneMode {
	if x != nil {
		return x.Modes
	}
	return nil
}

func (x *SceneModes) GetCurrentMode() string {
	if x != nil {
		return x.CurrentMode
	}
	return ""
}

func (x *SceneModes) GetCurrentScenePath() string {
	if x != nil {
		return x.CurrentScenePath
	}
	return ""
}

var File_grpc_engine_proto protoreflect.FileDescriptor

const file_grpc_engine_proto_rawDesc = "" +
	"\n" +
	"\x11grpc/engine.proto\x12\x04grpc\x1a\x1bgoogle/protobuf/empty.proto\"\xfb\x01\n" +
	"\rEngineRequest\x12-\n" +
	"\toperation\x18\x01 \x01(\x0e2\x0f.grpc.OperationR\toperation\x12.\n" +
	"\x05empty\x18\x02 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x05empty\x12&\n" +
	"\x06object\x18\x03 \x01(\v2\f.grpc.ObjectH\x00R\x06object\x12&\n" +
	"\x05scene\x18\x04 \x01(\v2\x0e.grpc.SceneRefH\x00R\x05scene\x123\n" +
	"\n" +
	"scene_mode\x18\x05 \x01(\v2\x12.grpc.SceneModeRefH\x00R\tsceneModeB\x06\n" +
	"\x04body\"\xaf\x02\n" +
	"\x0eEngineResponse\x12-\n" +
	"\toperation\x18\x01 \x01(\x0e2\x0f.grpc.OperationR\toperation\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12.\n" +
	"\x05empty\x18\x04 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x05empty\x12)\n" +
	"\aobjects\x18\x05 \x01(\v2\r.grpc.ObjectsH\x00R\aobjects\x12&\n" +
	"\x06object\x18\x06 \x01(\v2\f.grpc.ObjectH\x00R\x06object\x123\n" +
	"\vscene_modes\x18\a \x01(\v2\x10.grpc.SceneModesH\x00R\n" +
	"sceneModesB\x06\n" +
	"\x04body\"1\n" +
	"\aObjects\x12&\n" +
	"\aobjects\x18\x01 \x03(\v2\f.grpc.ObjectR\aobjects\"\x8b\x01\n" +
	"\x06Object\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12*\n" +
	"\blocation\x18\x03 \x01(\v2\x0e.grpc.LocationR\blocation\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x04R\bparentId\"\x85\x01\n" +
	"\bLocation\x12)\n" +
	"\bposition\x18\x01 \x01(\v2\r.grpc.Vector3R\bposition\x12)\n" +
	"\brotation\x18\x02 \x01(\v2\r.grpc.Vector4R\brotation\x12#\n" +
	"\x05scale\x18\x03 \x01(\v2\r.grpc.Vector3R\x05scale\"A\n" +
	"\aVector4\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\f\n" +
	"\x01w\x18\x04 \x01(\x02R\x01w\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"\x1e\n" +
	"\bSceneRef\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\"\n" +
	"\fSceneModeRef\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\"3\n" +
	"\tSceneMode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x84\x01\n" +
	"\n" +
	"SceneModes\x12%\n" +
	"\x05modes\x18\x01 \x03(\v2\x0f.grpc.SceneModeR\x05modes\x12!\n" +
	"\fcurrent_mode\x18\x02 \x01(\tR\vcurrentMode\x12,\n" +
	"\x12current_scene_path\x18\x03 \x01(\tR\x10currentScenePath*\xf6\x02\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OPERATION_GET_OBJECTS\x10\x01\x12\x18\n" +
	"\x14OPERATION_ADD_OBJECT\x10\x02\x12\x1b\n" +
	"\x17OPERATION_REMOVE_OBJECT\x10\x03\x12\x19\n" +
	"\x15OPERATION_MOVE_OBJECT\x10\x04\x12\x1b\n" +
	"\x17OPERATION_ROTATE_OBJECT\x10\x05\x12\x1a\n" +
	"\x16OPERATION_SCALE_OBJECT\x10\x06\x12\x1b\n" +
	"\x17OPERATION_UPDATE_OBJECT\x10\a\x12\x18\n" +
	"\x14OPERATION_LOAD_SCENE\x10\b\x12\x1d\n" +
	"\x19OPERATION_GET_SCENE_MODES\x10\t\x12\x1d\n" +
	"\x19OPERATION_LOAD_SCENE_MODE\x10\n" +
	"\x12\x18\n" +
	"\x14OPERATION_SET_PARENT\x10\v\x12\x19\n" +
	"\x15OPERATION_REMOVE_TREE\x10\f2A\n" +
	"\x06Engine\x127\n" +
	"\x06Stream\x12\x13.grpc.EngineRequest\x1a\x14.grpc.EngineResponse(\x010\x01B\x10Z\x0e3d-engine/grpcb\x06proto3"

var (
	file_grpc_engine_proto_rawDescOnce sync.Once
	file_grpc_engine_proto_rawDescData []byte
)

func file_grpc_engine_proto_rawDescGZIP() []byte {
	file_grpc_engine_proto_rawDescOnce.Do(func() {
		file_grpc_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_engine_proto_rawDesc), len(file_grpc_engine_proto_rawDesc)))
	})
	return file_grpc_engine_proto_rawDescData
}

var file_grpc_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_grpc_engine_proto_goTypes = []any{
	(Operation)(0),         // 0: grpc.Operation
	(*EngineRequest)(nil),  // 1: grpc.EngineRequest
	(*EngineResponse)(nil), // 2: grpc.EngineResponse
	(*Objects)(nil),        // 3: grpc.Objects
	(*Object)(nil),         // 4: grpc.Object
	(*Location)(nil),       // 5: grpc.Location
	(*Vector4)(nil),        // 6: grpc.Vector4
	(*Vector3)(nil),        // 7: grpc.Vector3
	(*SceneRef)(nil),       // 8: grpc.SceneRef
	(*SceneModeRef)(nil),   // 9: grpc.SceneModeRef
	(*SceneMode)(nil),      // 10: grpc.SceneMode
	(*SceneModes)(nil),     // 11: grpc.SceneModes
	(*emptypb.Empty)(nil),  // 12: google.protobuf.Empty
}
var file_grpc_engine_proto_depIdxs = []int32{
	0,  // 0: grpc.EngineRequest.operation:type_name -> grpc.Operation
	12, // 1: grpc.EngineRequest.empty:type_name -> google.protobuf.Empty
	4,  // 2: grpc.EngineRequest.object:type_name -> grpc.Object
	8,  // 3: grpc.EngineRequest.scene:type_name -> grpc.SceneRef
	9,  // 4: grpc.EngineRequest.scene_mode:type_name -> grpc.SceneModeRef
	0,  // 5: grpc.EngineResponse.operation:type_name -> grpc.Operation
	12, // 6: grpc.EngineResponse.empty:type_name -> google.protobuf.Empty
	3,  // 7: grpc.EngineResponse.objects:type_name -> grpc.Objects
	4,  // 8: grpc.EngineResponse.object:type_name -> grpc.Object
	11, // 9: grpc.EngineResponse.scene_modes:type_name -> grpc.SceneModes
	4,  // 10: grpc.Objects.objects:type_name -> grpc.Object
	5,  // 11: grpc.Object.location:type_name -> grpc.Location
	7,  // 12: grpc.Location.position:type_name -> grpc.Vector3
	6,  // 13: grpc.Location.rotation:type_name -> grpc.Vector4
	7,  // 14: grpc.Location.scale:type_name -> grpc.Vector3
	10, // 15: grpc.SceneModes.modes:type_name -> grpc.SceneMode
	1,  // 16: grpc.Engine.Stream:input_type -> grpc.EngineRequest
	2,  // 17: grpc.Engine.Stream:output_type -> grpc.EngineResponse
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_grpc_engine_proto_init() }
func file_grpc_engine_proto_init() {
	if File_grpc_engine_proto != nil {
		return
	}
	file_grpc_engine_proto_msgTypes[0].OneofWrappers = []any{
		(*EngineRequest_Empty)(nil),
		(*EngineRequest_Object)(nil),
		(*EngineRequest_Scene)(nil),
		(*EngineRequest_SceneMode)(nil),
	}
	file_grpc_engine_proto_msgTypes[1].OneofWrappers = []any{
		(*EngineResponse_Empty)(nil),
		(*EngineResponse_Objects)(nil),
		(*EngineResponse_Object)(nil),
		(*EngineResponse_SceneModes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_engine_proto_rawDesc), len(file_grpc_engine_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_engine_proto_goTypes,
		DependencyIndexes: file_grpc_engine_proto_depIdxs,
		EnumInfos:         file_grpc_engine_proto_enumTypes,
		MessageInfos:      file_grpc_engine_proto_msgTypes,
	}.Build()
	File_grpc_engine_proto = out.File
	file_grpc_engine_proto_goTypes = nil
	file_grpc_engine_proto_depIdxs = nil
}
